spring:
  application:
    name: course-management

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  datasource:
    url: jdbc:h2:mem:courseapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "never"

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

app:
  plugin:
    url: ""
