name: CI/GitHub

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21-jdk-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build, test, package
        run: ./mvnw -B clean package

      - name: Upload jar artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: target/*.jar

  sast:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: semgrep/semgrep:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep (SARIF)
        run: semgrep scan --config auto --sarif --output semgrep.sarif .
        continue-on-error: true

      - name: Upload SARIF to GitHub code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
  sca:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.9.11-eclipse-temurin-21-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP
        run: mvn -B org.owasp:dependency-check-maven:check -Dnvd.api.key=${{ secrets.NVD_API_KEY }}

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
